# Generated by Django 3.1.6 on 2021-03-23 19:02

from django.db import migrations, models
import giftSomeone.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210323_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=giftSomeone.helpers.PathAndRenameFile('products_images')),
        ),
    ]
