# Generated by Django 3.1.6 on 2021-03-29 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210329_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billing',
            new_name='BillingAddress',
        ),
    ]
