# Generated by Django 3.1.6 on 2021-03-29 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20210329_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingAddress', to=settings.AUTH_USER_MODEL),
        ),
    ]
